### ISSUE TITLE
python request.get is hanging while curl works

### ISSUE THREAD

**Issue by alexbaras** [NCIEVS/evsrestapi-client-SDK#7] opened 2023-03-18 13:46 UTC
Hello,

I cannot figure out why from my computer this command works

```
curl -X GET "https://api-evsrest.nci.nih.gov/api/v1/concept/ncit/C2919?include=summary" -H "accept: application/json"
```

but with python 3.9.15 and requests 2.28.1 it hangs 

```
headers = {'accept': 'application/json'}
r = requests.get('https://api-evsrest.nci.nih.gov/api/v1/concept/ncit/C2919?include=summary', headers=headers)
```

Seems very odd?

**Comment by peter-va** [comment] 2023-03-19 07:34
That is indeed very odd. I was able to reproduce it fine. A few minutes of late-night research turned up this from the docs of the request library: 

`"Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner. By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more." `

Source directly from the docs: https://docs.python-requests.org/en/latest/user/advanced/#timeouts
Seems like we should have some timeouts on these calls. I found that adding timeout=0.5 worked pretty consistently on my end, so your code example would end up like this:

`headers = {'accept': 'application/json'}
r = requests.get('https://api-evsrest.nci.nih.gov/api/v1/concept/ncit/C2919?include=summary', headers=headers, timeout=0.5)`

I'll be further investigating this a bit on Monday but hopefully that is at least a temporary solution.

**Comment by alexbaras** [comment] 2023-03-19 12:01
I ran across that too, but was very surprised to see that including that actually resulted in a complete message being returned. I would have thought that this just would have stopped the process from hanging by aborting after timeout period. I confirm that this is a temp fix for this specific call, but I have never had to use the request timeout param across many many APIs. 

Also, while I have you ... I was trying check if a given ncit code was anywhere in the path from root to a second ncit code. I was going to use the pathsFromRoot endpoint - but wanted to check to see if there was any better way. That call can talk some time so I set the timeout to 60 for now on that.

**Comment by peter-va** [comment] 2023-03-20 04:45
Assuming I understand your use case correctly (that you want to see if ncit concept B is somewhere in the paths from root going to ncit concept A), I can't think of a clean way to do that. I think your current way is the best at the moment. That could be worth implementing if it's a common use case.

**Comment by peter-va** [comment] 2023-03-20 20:23
Actually, pathsToAncestor somewhat does the job as well: /concept/ncit/CodeC/pathsToAncestor/CodeB will tell you if CodeB is an ancestor of CodeC. It won't tell you under what root it's an ancestor, but it will tell you that it *is* an ancestor and therefore somewhere in the path.

**Comment by alexbaras** [comment] 2023-03-21 02:13
Thanks for this. It looks like this is now working without needing the timeout param. That being said, I think that a timeout should be there in general as good practice but should not be required for the API to return, right?

**Comment by peter-va** [comment] 2023-03-21 19:54
Yes I'd say that's correct.

**Comment by gaaliciA1990** [comment] 2024-02-03 00:58
@peter-va @alexbaras  There's been no update on this ticket since March of 2023. Can we resolve this?

**Comment by gaaliciA1990** [comment] 2024-09-16 15:41
Closing issue as no update posted in over a year

**Closed by gaaliciA1990** 2024-09-16 15:41 UTC
